### ISSUE TITLE
prompt

### ISSUE THREAD

**Issue by planet4** [alvaldes/aterm#15]
Thanks for sharing this. I have been looking for some simple, yet advanced way of a terminal portfolio. Is there anyway of changing the prompt visitor@aterm.com? Were able to change one but it seems to get back when typing more. Could not find this in the code.

**Comment by alvaldes** [comment]
Hi ✋🏻
Basically, there are 3 places where the host is changed
<img width="584" alt="image" src="https://github.com/alvaldes/aterm/assets/44712690/c91d0770-bc8c-4314-85a1-50d9723387cc">
You can do a search for `visitor@aterm.com` and you will see that they are for the following functionalities:
- history
- code auto-completion (TABx2)
- and the current line

**Note:** You can take this out to a constant and thus only have to modify it in 1 single place.
